---
title: "C28105 | Microsoft Docs"
ms.custom: ""
ms.date: "11/04/2016"
ms.reviewer: ""
ms.suite: ""
ms.technology: 
  - "vs-devops-test"
ms.tgt_pltfrm: ""
ms.topic: "article"
f1_keywords: 
  - "C28105"
helpviewer_keywords: 
  - "C28105"
ms.assetid: 5afdec78-30eb-470c-980f-93d0cb3e74cc
caps.latest.revision: 3
author: "corob-msft"
ms.author: "corob"
manager: "ghogen"
caps.handback.revision: 3
---
# C28105
[!INCLUDE[vs2017banner](../code-quality/includes/vs2017banner.md)]

Avertissement C28105 : Ressource disjointe en raison d'une exception  
  
 La ressource spécifiée n'est pas libérée lorsqu'une exception est levée.  L'instruction spécifiée par le chemin d'accès peut lever une exception.  Cet avertissement est semblable à l'avertissement [C28103](../code-quality/c28103.md), sauf que dans ce cas une exception est sous\-entendue.  
  
## Exemple  
 L'exemple de code suivant génère cet avertissement :  
  
```  
res = KeSaveFloatingPointState(buffer);  
  
res = AllocateResource(Resource);  
char *p2 = new char[10]; // could throw  
  
delete[] p2;  
FreeResource(Resource)  
```  
  
 L'exemple de code suivant permet d'éviter cet avertissement :  
  
```  
res = AllocateResource(Resource);  
char *p2;  
  
try {  
    p2 = new char[10];  
} catch (std::bad_alloc *e) {  
    // just handle the throw  
    ;  
}  
FreeResource(Resource)  
```