---
title: C28105
ms.date: 11/04/2016
ms.technology: vs-ide-code-analysis
ms.topic: reference
f1_keywords:
- C28105
helpviewer_keywords:
- C28105
ms.assetid: 5afdec78-30eb-470c-980f-93d0cb3e74cc
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: 455e06476d6841f468a64d45b350e45f3e8d1a75
ms.sourcegitcommit: 42ea834b446ac65c679fa1043f853bea5f1c9c95
ms.translationtype: MT
ms.contentlocale: fr-FR
ms.lasthandoff: 04/19/2018
---
# <a name="c28105"></a>C28105
Avertissement C28105 : Une fuite de ressources en raison d’une exception.

 La ressource spécifiée n’est pas libérée lorsqu’une exception est levée. L’instruction spécifiée par le chemin d’accès peut lever une exception. Cet avertissement est similaire à l’avertissement [C28103](../code-quality/c28103.md), sauf que dans ce cas une exception est impliquée.

## <a name="example"></a>Exemple
 L'exemple de code suivant génère cet avertissement :

```
res = KeSaveFloatingPointState(buffer);

res = AllocateResource(Resource);
char *p2 = new char[10]; // could throw

delete[] p2;
FreeResource(Resource)
```

 L'exemple de code suivant évite cet avertissement :

```
res = AllocateResource(Resource);
char *p2;

try {
    p2 = new char[10];
} catch (std::bad_alloc *e) {
    // just handle the throw
    ;
}
FreeResource(Resource)
```