---
title: C28105 | Documents Microsoft
ms.custom: ''
ms.date: 11/04/2016
ms.technology:
- vs-ide-code-analysis
ms.topic: conceptual
f1_keywords:
- C28105
helpviewer_keywords:
- C28105
ms.assetid: 5afdec78-30eb-470c-980f-93d0cb3e74cc
author: mikeblome
ms.author: mblome
manager: douge
ms.workload:
- multiple
ms.openlocfilehash: f13afe72d53f8765cc7d1e1e2540b23f2d378d56
ms.sourcegitcommit: 6a9d5bd75e50947659fd6c837111a6a547884e2a
ms.translationtype: MT
ms.contentlocale: fr-FR
ms.lasthandoff: 04/16/2018
---
# <a name="c28105"></a>C28105
Avertissement C28105 : Une fuite de ressources en raison d’une exception.  
  
 La ressource spécifiée n’est pas libérée lorsqu’une exception est levée. L’instruction spécifiée par le chemin d’accès peut lever une exception. Cet avertissement est similaire à l’avertissement [C28103](../code-quality/c28103.md), sauf que dans ce cas une exception est impliquée.  
  
## <a name="example"></a>Exemple  
 L'exemple de code suivant génère cet avertissement :  
  
```  
res = KeSaveFloatingPointState(buffer);  
  
res = AllocateResource(Resource);  
char *p2 = new char[10]; // could throw  
  
delete[] p2;  
FreeResource(Resource)  
```  
  
 L'exemple de code suivant évite cet avertissement :  
  
```  
res = AllocateResource(Resource);  
char *p2;  
  
try {  
    p2 = new char[10];  
} catch (std::bad_alloc *e) {  
    // just handle the throw  
    ;  
}  
FreeResource(Resource)  
```