---
title: C6312 | Documents Microsoft
ms.custom: ''
ms.date: 11/04/2016
ms.technology:
- vs-ide-code-analysis
ms.topic: conceptual
f1_keywords:
- C6312
helpviewer_keywords:
- C6312
ms.assetid: 1fc8b9a1-e6ba-4799-84c3-31f289576cca
author: mikeblome
ms.author: mblome
manager: douge
ms.workload:
- multiple
ms.openlocfilehash: 766a3c670a41bb4f915c94c3f5d0df09fde11afe
ms.sourcegitcommit: 6a9d5bd75e50947659fd6c837111a6a547884e2a
ms.translationtype: MT
ms.contentlocale: fr-FR
ms.lasthandoff: 04/16/2018
---
# <a name="c6312"></a>C6312
avertissement C6312 : boucle infinie Possible : utilisation de la constante EXCEPTION_CONTINUE_EXECUTION dans l’expression de filtre d’exception d’un bloc try-à l’exception  
  
 Cet avertissement indique l’utilisation de la constante `EXCEPTION_CONTINUE_EXECUTION` (ou une autre constante égale à -1) dans l’expression de filtre d’un gestionnaire d’exceptions structuré. Utilisation de la valeur de constante `EXCEPTION_CONTINUE_EXECUTION` peut entraîner une boucle infinie. Par exemple, si une exception a été levée par le matériel, l’instruction qui a provoqué l’exception est redémarrée. Si l’adresse qui a provoqué l’exception est encore erronée, une autre exception se produira et être gérée de la même façon. Cela provoque une boucle infinie.  
  
 Un appel explicite à `RaiseException` ne provoquera pas directement une boucle infinie, mais poursuit l’exécution du code dans le bloc protégé. Cela peut être inattendu et peut entraîner une boucle infinie si `RaiseException` a été utilisé pour éviter de déréférencer un pointeur non valide.  
  
 En règle générale, `EXCEPTION_CONTINUE_EXECUTION` doit être retourné que par une fonction appelée dans l’expression de filtre qui a une chance de corriger soit le pointeur qui a provoqué l’exception, soit la mémoire sous-jacente.  
  
## <a name="example"></a>Exemple  
 Le code suivant génère cet avertissement :  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
void f (char *ptr)  
{  
  __try   
  {  
    // exception occurs if the caller passes null ptr  
    // code...     
   *ptr = '\0';  
  }   
  __except (EXCEPTION_CONTINUE_EXECUTION)  
    // When EXCEPTION_CONTINUE_EXECUTION is used, the handler  
    //  block of the structured exception handler is not executed.   
  {  
    puts("This block is never executed");  
  }  
}  
```  
  
 Pour corriger cet avertissement, utilisez le code suivant :  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
void f (char *ptr)  
{  
  __try   
  {  
    // exception occurs if the caller passes null ptr  
    // code...  
    *ptr = '\0';  
  }   
  __except (GetExceptionCode()== EXCEPTION_ACCESS_VIOLATION ?   
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)   
  {  
    puts("Error Occurred");  
  }  
}  
```